// automatically generated by the FlatBuffers compiler, do not modify

package Serializer;

public final class Action {
  private Action() { }
  public static final short CSS_RULE_SNAPSHOT = 0;
  public static final short FOCUS = 1;
  public static final short FOCUS_IN = 2;
  public static final short FOCUS_OUT = 3;
  public static final short MOUSE_CLICK = 4;
  public static final short MOUSE_OVER = 5;
  public static final short MOUSE_POSITION = 6;
  public static final short MUTATION_EVENT = 7;
  public static final short VIDEO_PAUSE = 8;
  public static final short VIDEO_PLAY = 9;
  public static final short VIDEO_TIME_UPDATE = 10;
  public static final short VIDEO_VOLUME_CHANGE = 11;
  public static final short INPUT = 12;
  public static final short INPUT_PROGRAMMATIC_CHANGE = 13;
  public static final short SCROLL = 14;
  public static final short SELECTION = 15;
  public static final short URL_CHANGED = 16;
  public static final short VISIBILITY = 17;
  public static final short WINDOW_CLOSE = 18;
  public static final short VIEWPORT_CHANGED = 19;
  public static final short FINISHED_SNAPSHOT = 20;
  public static final short DOM_SNAPSHOT = 21;
  public static final short PAGE_SNAPSHOT_EVENTS = 22;
  public static final short CANVAS_UPDATE = 23;
  public static final short ERROR = 24;
  public static final short ERROR_OUR = 25;
  public static final short IDENTIFY = 26;
  public static final short SET_USER_INFO = 27;
  public static final short TOUCH_CANCEL = 28;
  public static final short TOUCH_END = 29;
  public static final short TOUCH_MOVE = 30;
  public static final short TOUCH_START = 31;
  public static final short PRESS = 32;
  public static final short DOUBLE_TAP = 33;
  public static final short SWIPE_RIGHT = 34;
  public static final short SWIPE_LEFT = 35;
  public static final short SWIPE_DOWN = 36;
  public static final short SWIPE_UP = 37;
  public static final short IDLE_TIME = 38;
  public static final short CUSTOM_EVENT = 39;

  public static final String[] names = { "CSS_RULE_SNAPSHOT", "FOCUS", "FOCUS_IN", "FOCUS_OUT", "MOUSE_CLICK", "MOUSE_OVER", "MOUSE_POSITION", "MUTATION_EVENT", "VIDEO_PAUSE", "VIDEO_PLAY", "VIDEO_TIME_UPDATE", "VIDEO_VOLUME_CHANGE", "INPUT", "INPUT_PROGRAMMATIC_CHANGE", "SCROLL", "SELECTION", "URL_CHANGED", "VISIBILITY", "WINDOW_CLOSE", "VIEWPORT_CHANGED", "FINISHED_SNAPSHOT", "DOM_SNAPSHOT", "PAGE_SNAPSHOT_EVENTS", "CANVAS_UPDATE", "ERROR", "ERROR_OUR", "IDENTIFY", "SET_USER_INFO", "TOUCH_CANCEL", "TOUCH_END", "TOUCH_MOVE", "TOUCH_START", "PRESS", "DOUBLE_TAP", "SWIPE_RIGHT", "SWIPE_LEFT", "SWIPE_DOWN", "SWIPE_UP", "IDLE_TIME", "CUSTOM_EVENT", };

  public static String name(int e) { return names[e]; }
}

