// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Serializer

import "strconv"

type Action int16

const (
	ActionCSS_RULE_SNAPSHOT         Action = 0
	ActionFOCUS                     Action = 1
	ActionFOCUS_IN                  Action = 2
	ActionFOCUS_OUT                 Action = 3
	ActionMOUSE_CLICK               Action = 4
	ActionMOUSE_OVER                Action = 5
	ActionMOUSE_POSITION            Action = 6
	ActionMUTATION_EVENT            Action = 7
	ActionVIDEO_PAUSE               Action = 8
	ActionVIDEO_PLAY                Action = 9
	ActionVIDEO_TIME_UPDATE         Action = 10
	ActionVIDEO_VOLUME_CHANGE       Action = 11
	ActionINPUT                     Action = 12
	ActionINPUT_PROGRAMMATIC_CHANGE Action = 13
	ActionSCROLL                    Action = 14
	ActionSELECTION                 Action = 15
	ActionURL_CHANGED               Action = 16
	ActionVISIBILITY                Action = 17
	ActionWINDOW_CLOSE              Action = 18
	ActionVIEWPORT_CHANGED          Action = 19
	ActionFINISHED_SNAPSHOT         Action = 20
	ActionDOM_SNAPSHOT              Action = 21
	ActionPAGE_SNAPSHOT_EVENTS      Action = 22
	ActionCANVAS_UPDATE             Action = 23
	ActionERROR                     Action = 24
	ActionERROR_OUR                 Action = 25
	ActionIDENTIFY                  Action = 26
	ActionSET_USER_INFO             Action = 27
	ActionTOUCH_CANCEL              Action = 28
	ActionTOUCH_END                 Action = 29
	ActionTOUCH_MOVE                Action = 30
	ActionTOUCH_START               Action = 31
	ActionPRESS                     Action = 32
	ActionDOUBLE_TAP                Action = 33
	ActionSWIPE_RIGHT               Action = 34
	ActionSWIPE_LEFT                Action = 35
	ActionSWIPE_DOWN                Action = 36
	ActionSWIPE_UP                  Action = 37
	ActionIDLE_TIME                 Action = 38
	ActionCUSTOM_EVENT              Action = 39
)

var EnumNamesAction = map[Action]string{
	ActionCSS_RULE_SNAPSHOT:         "CSS_RULE_SNAPSHOT",
	ActionFOCUS:                     "FOCUS",
	ActionFOCUS_IN:                  "FOCUS_IN",
	ActionFOCUS_OUT:                 "FOCUS_OUT",
	ActionMOUSE_CLICK:               "MOUSE_CLICK",
	ActionMOUSE_OVER:                "MOUSE_OVER",
	ActionMOUSE_POSITION:            "MOUSE_POSITION",
	ActionMUTATION_EVENT:            "MUTATION_EVENT",
	ActionVIDEO_PAUSE:               "VIDEO_PAUSE",
	ActionVIDEO_PLAY:                "VIDEO_PLAY",
	ActionVIDEO_TIME_UPDATE:         "VIDEO_TIME_UPDATE",
	ActionVIDEO_VOLUME_CHANGE:       "VIDEO_VOLUME_CHANGE",
	ActionINPUT:                     "INPUT",
	ActionINPUT_PROGRAMMATIC_CHANGE: "INPUT_PROGRAMMATIC_CHANGE",
	ActionSCROLL:                    "SCROLL",
	ActionSELECTION:                 "SELECTION",
	ActionURL_CHANGED:               "URL_CHANGED",
	ActionVISIBILITY:                "VISIBILITY",
	ActionWINDOW_CLOSE:              "WINDOW_CLOSE",
	ActionVIEWPORT_CHANGED:          "VIEWPORT_CHANGED",
	ActionFINISHED_SNAPSHOT:         "FINISHED_SNAPSHOT",
	ActionDOM_SNAPSHOT:              "DOM_SNAPSHOT",
	ActionPAGE_SNAPSHOT_EVENTS:      "PAGE_SNAPSHOT_EVENTS",
	ActionCANVAS_UPDATE:             "CANVAS_UPDATE",
	ActionERROR:                     "ERROR",
	ActionERROR_OUR:                 "ERROR_OUR",
	ActionIDENTIFY:                  "IDENTIFY",
	ActionSET_USER_INFO:             "SET_USER_INFO",
	ActionTOUCH_CANCEL:              "TOUCH_CANCEL",
	ActionTOUCH_END:                 "TOUCH_END",
	ActionTOUCH_MOVE:                "TOUCH_MOVE",
	ActionTOUCH_START:               "TOUCH_START",
	ActionPRESS:                     "PRESS",
	ActionDOUBLE_TAP:                "DOUBLE_TAP",
	ActionSWIPE_RIGHT:               "SWIPE_RIGHT",
	ActionSWIPE_LEFT:                "SWIPE_LEFT",
	ActionSWIPE_DOWN:                "SWIPE_DOWN",
	ActionSWIPE_UP:                  "SWIPE_UP",
	ActionIDLE_TIME:                 "IDLE_TIME",
	ActionCUSTOM_EVENT:              "CUSTOM_EVENT",
}

var EnumValuesAction = map[string]Action{
	"CSS_RULE_SNAPSHOT":         ActionCSS_RULE_SNAPSHOT,
	"FOCUS":                     ActionFOCUS,
	"FOCUS_IN":                  ActionFOCUS_IN,
	"FOCUS_OUT":                 ActionFOCUS_OUT,
	"MOUSE_CLICK":               ActionMOUSE_CLICK,
	"MOUSE_OVER":                ActionMOUSE_OVER,
	"MOUSE_POSITION":            ActionMOUSE_POSITION,
	"MUTATION_EVENT":            ActionMUTATION_EVENT,
	"VIDEO_PAUSE":               ActionVIDEO_PAUSE,
	"VIDEO_PLAY":                ActionVIDEO_PLAY,
	"VIDEO_TIME_UPDATE":         ActionVIDEO_TIME_UPDATE,
	"VIDEO_VOLUME_CHANGE":       ActionVIDEO_VOLUME_CHANGE,
	"INPUT":                     ActionINPUT,
	"INPUT_PROGRAMMATIC_CHANGE": ActionINPUT_PROGRAMMATIC_CHANGE,
	"SCROLL":                    ActionSCROLL,
	"SELECTION":                 ActionSELECTION,
	"URL_CHANGED":               ActionURL_CHANGED,
	"VISIBILITY":                ActionVISIBILITY,
	"WINDOW_CLOSE":              ActionWINDOW_CLOSE,
	"VIEWPORT_CHANGED":          ActionVIEWPORT_CHANGED,
	"FINISHED_SNAPSHOT":         ActionFINISHED_SNAPSHOT,
	"DOM_SNAPSHOT":              ActionDOM_SNAPSHOT,
	"PAGE_SNAPSHOT_EVENTS":      ActionPAGE_SNAPSHOT_EVENTS,
	"CANVAS_UPDATE":             ActionCANVAS_UPDATE,
	"ERROR":                     ActionERROR,
	"ERROR_OUR":                 ActionERROR_OUR,
	"IDENTIFY":                  ActionIDENTIFY,
	"SET_USER_INFO":             ActionSET_USER_INFO,
	"TOUCH_CANCEL":              ActionTOUCH_CANCEL,
	"TOUCH_END":                 ActionTOUCH_END,
	"TOUCH_MOVE":                ActionTOUCH_MOVE,
	"TOUCH_START":               ActionTOUCH_START,
	"PRESS":                     ActionPRESS,
	"DOUBLE_TAP":                ActionDOUBLE_TAP,
	"SWIPE_RIGHT":               ActionSWIPE_RIGHT,
	"SWIPE_LEFT":                ActionSWIPE_LEFT,
	"SWIPE_DOWN":                ActionSWIPE_DOWN,
	"SWIPE_UP":                  ActionSWIPE_UP,
	"IDLE_TIME":                 ActionIDLE_TIME,
	"CUSTOM_EVENT":              ActionCUSTOM_EVENT,
}

func (v Action) String() string {
	if s, ok := EnumNamesAction[v]; ok {
		return s
	}
	return "Action(" + strconv.FormatInt(int64(v), 10) + ")"
}
