// automatically generated by the FlatBuffers compiler, do not modify

package Serializer;

public final class DataType {
  private DataType() { }
  public static final byte NONE = 0;
  public static final byte StringList = 1;
  public static final byte MutationData = 2;

  public static final String[] names = { "NONE", "StringList", "MutationData", };

  public static String name(int e) { return names[e]; }
}

